version: "3"

services:
  php:
    container_name: lrc-php
    build:
      context: .docker
      dockerfile: php-image/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=07fdfe4039e2eb0f8fed8796e212fafa
      - DB_CONNECTION=mysql
      - DB_DATABASE=lrc
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - 9000
    depends_on:
      - db

  db:
    container_name: lrc-db
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3309:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lrc
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  nginx:
    container_name: lrc-nginx
    image: nginx:1.17
    links:
      - php
    ports:
      - 8000:80
    volumes:
      - .docker/nginx-image/nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

volumes:
  mysql:
